#!/bin/bash
# ================================================================
# Modern AI-Powered Infrastructure Pipeline (Day 1: The Beautiful Lie)
# ================================================================
# This script demonstrates the "solved problem" of AI code generation
# Spoiler: Generation works perfectly. Operations is the hard part.
# ================================================================

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# ================================================================
# [1] PROMPT: Human describes infrastructure need
# ================================================================
echo -e "${CYAN}[1] PROMPT${NC}"
echo "\"Create encrypted S3 bucket with versioning and lifecycle rules\""
echo ""
sleep 1

# ================================================================
# [2] LLM GENERATES: AI writes Terraform code
# ================================================================
echo -e "${CYAN}[2] LLM GENERATES${NC}"
echo "Calling Claude Sonnet 4.6 API..."
sleep 1

# Simulate LLM generation (in reality, this would call OpenAI/Anthropic API)
cat > /tmp/generated_s3.tf << 'EOF'
# Auto-generated by AI (Claude Sonnet 4.6)
# Prompt: "Create encrypted S3 bucket with versioning and lifecycle rules"

resource "aws_s3_bucket" "data_store" {
  bucket = "example-data-store-${random_id.suffix.hex}"

  tags = {
    Name        = "Data Store"
    Environment = "production"
    ManagedBy   = "Terraform"
    GeneratedBy = "AI"
  }
}

resource "random_id" "suffix" {
  byte_length = 4
}

resource "aws_s3_bucket_versioning" "data_store" {
  bucket = aws_s3_bucket.data_store.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "data_store" {
  bucket = aws_s3_bucket.data_store.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "data_store" {
  bucket = aws_s3_bucket.data_store.id

  rule {
    id     = "archive-old-objects"
    status = "Enabled"

    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }

    transition {
      days          = 90
      storage_class = "GLACIER"
    }

    expiration {
      days = 365
    }
  }
}

output "bucket_name" {
  value       = aws_s3_bucket.data_store.id
  description = "The name of the S3 bucket"
}
EOF

echo -e "${GREEN}✓${NC} Generated 47 lines of HCL"
echo -e "${GREEN}✓${NC} Correct AWS provider syntax"
echo -e "${GREEN}✓${NC} Follows Terraform best practices"
echo ""
sleep 1

# ================================================================
# [3] SECURITY SCAN: Automated security validation
# ================================================================
echo -e "${CYAN}[3] SECURITY SCAN${NC}"
echo "Running Checkov + tfsec..."
sleep 1

# Simulate security scans (in reality, these would run actual tools)
echo -e "${GREEN}✓${NC} Checkov: 0 critical issues"
echo "  - Encryption: PASS (AES256 enabled)"
echo "  - Versioning: PASS (enabled)"
echo "  - Public access: PASS (blocked by default)"
echo ""

echo -e "${GREEN}✓${NC} tfsec: 0 violations"
echo "  - aws-s3-enable-bucket-encryption: PASS"
echo "  - aws-s3-enable-versioning: PASS"
echo "  - aws-s3-enable-bucket-logging: SKIP (optional)"
echo ""
sleep 1

# ================================================================
# [4] PR REVIEW: Human approval (or auto-approve)
# ================================================================
echo -e "${CYAN}[4] PR REVIEW${NC}"
echo "Creating pull request..."
sleep 1

cat << 'EOF'
╔════════════════════════════════════════════════════════════╗
║ Pull Request #42: Add encrypted S3 bucket                 ║
╠════════════════════════════════════════════════════════════╣
║ Generated by: Claude Sonnet 4.6                           ║
║ Security scan: ✓ PASSED                                   ║
║ Terraform plan: ✓ 4 resources to add                      ║
║ Changes: +47 -0 lines                                      ║
║                                                            ║
║ Reviewer: @platform-team                                  ║
║ Status: APPROVED ✓                                        ║
║ Merged to: main                                           ║
╚════════════════════════════════════════════════════════════╝
EOF

echo ""
sleep 1

# ================================================================
# [5] CI/CD: Terraform plan + apply
# ================================================================
echo -e "${CYAN}[5] CI/CD${NC}"
echo "Running terraform plan..."
sleep 1

cat << 'EOF'
Terraform will perform the following actions:

  # aws_s3_bucket.data_store will be created
  + resource "aws_s3_bucket" "data_store" {
      + bucket = "example-data-store-a1b2c3d4"
      + tags   = {
          + "Environment" = "production"
          + "GeneratedBy" = "AI"
          + "ManagedBy"   = "Terraform"
          + "Name"        = "Data Store"
        }
    }

  # aws_s3_bucket_versioning.data_store will be created
  + resource "aws_s3_bucket_versioning" "data_store" {
      + versioning_configuration {
          + status = "Enabled"
        }
    }

  # aws_s3_bucket_server_side_encryption_configuration.data_store will be created
  # aws_s3_bucket_lifecycle_configuration.data_store will be created

Plan: 4 to add, 0 to change, 0 to destroy.
EOF

echo ""
echo "Running terraform apply..."
sleep 2

echo -e "${GREEN}✓${NC} Apply complete! Resources: 4 added, 0 changed, 0 destroyed"
echo ""
sleep 1

# ================================================================
# [6] LIVE: All systems operational
# ================================================================
echo -e "${CYAN}[6] LIVE${NC}"
echo -e "${GREEN}✓${NC} Infrastructure provisioned"
echo -e "${GREEN}✓${NC} Encryption enabled (AES256)"
echo -e "${GREEN}✓${NC} Versioning active"
echo -e "${GREEN}✓${NC} Lifecycle rules configured"
echo -e "${GREEN}✓${NC} All systems operational"
echo ""

# ================================================================
# THE BEAUTIFUL LIE
# ================================================================
cat << 'EOF'

╔══════════════════════════════════════════════════════════════╗
║                     🎉 SUCCESS! 🎉                          ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  AI CODE GENERATION WORKS                                    ║
║                                                              ║
║  From prompt to production in < 10 minutes                   ║
║  - Perfect syntax                                            ║
║  - Security validated                                        ║
║  - Best practices followed                                   ║
║  - Infrastructure deployed                                   ║
║                                                              ║
║  THE GENERATION PROBLEM IS SOLVED.                           ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

EOF

echo -e "${YELLOW}But wait...${NC}"
echo ""
sleep 2

cat << 'EOF'
╔══════════════════════════════════════════════════════════════╗
║                    ⚠️  DAY 2 REALITY ⚠️                     ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  THE OPERATIONS PROBLEM HAS NOT STARTED                      ║
║                                                              ║
║  What happens when:                                          ║
║  - Someone modifies the bucket via Console?                  ║
║  - A Lambda function changes lifecycle rules?                ║
║  - An SRE disables versioning during an incident?            ║
║  - Infrastructure drifts from the Terraform state?           ║
║                                                              ║
║  That's the hard part.                                       ║
║  That's what the rest of this talk is about.                 ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

EOF

echo ""
echo -e "${CYAN}Generated infrastructure:${NC}"
echo "  Bucket: example-data-store-a1b2c3d4"
echo "  Files: /tmp/generated_s3.tf"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Wait 24 hours"
echo "  2. Check for drift (someone WILL modify it)"
echo "  3. Realize detection alone isn't enough"
echo "  4. Build the system described in slides 6-29"
echo ""
echo -e "${GREEN}Generation problem: SOLVED ✓${NC}"
echo -e "${RED}Operations problem: UNSOLVED ✗${NC}"
echo ""

# ================================================================
# DEMO MODE: Show the generated file
# ================================================================
if [ "$1" == "--show-code" ]; then
    echo ""
    echo -e "${CYAN}Generated Terraform code:${NC}"
    echo "─────────────────────────────────────────────────────────────"
    cat /tmp/generated_s3.tf
    echo "─────────────────────────────────────────────────────────────"
fi

echo ""
echo "This is Slide 3: The Beautiful Lie - Day 1 Solved"
echo "The rest of the presentation solves Day 2+: Operations"
